### PR TITLE
Update dependency to Cake 3

### PR DESCRIPTION
**Pull request by bdukes**
I've tested that these changes allow [our build](https://github.com/dnnsoftware/Dnn.Platform/tree/develop/Build) to work successfully when targeting Cake 3. Thanks!

### CODE REVIEW

**Comment by nils-a** [comment]
@bdukes Thank you for getting this done. Are you in a position to rebase this PR?

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by bdukes** [comment]
I've rebased my branch, let me know if there's anything else I can do. Thanks!

**Comment by nils-a** [comment]
@bdukes  your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
